name: CI Windows

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Build Windows Executables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Docker Build
        run: docker build .
